# Generated by Django 4.2.7 on 2025-10-14 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_seed_routes_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stop',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='route',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='route',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='route',
            name='estimated_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='lon',
        ),
        migrations.AlterField(
            model_name='route',
            name='base_fare',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_type',
            field=models.CharField(choices=[('incity', 'In-city'), ('outercity', 'Outer-city')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stop',
            name='fare',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stop',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.route'),
        ),
    ]
