# Generated by Django 4.2.7 on 2025-10-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_stop_options_remove_route_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_type',
            field=models.CharField(choices=[('intercity', 'Intercity'), ('outercity', 'Outer City')], max_length=20),
        ),
    ]
