# Generated by Django 4.2.7 on 2025-10-21 09:18

from django.db import migrations

def update_route_types(apps, schema_editor):
    Route = apps.get_model('routes', 'Route')
    # Update any old route_type values to the new one
    Route.objects.filter(route_type__in=['incity', 'In-city']).update(route_type='intercity')


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_alter_route_route_type'),
    ]

    operations = [
        migrations.RunPython(update_route_types),
    ]
