# Generated by Django 4.2.7 on 2025-09-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
