# Generated by Django 4.2.7 on 2025-10-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_bus_route'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['id']},
        ),
    ]
