# Generated by Django 4.2.7 on 2025-10-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_alter_bus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_type',
            field=models.CharField(choices=[('incity', 'In-city'), ('outercity', 'Outer-city')], default='incity', max_length=20),
        ),
    ]
