# Generated by Django 4.2.7 on 2025-10-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_bus_bus_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('under_maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='active', max_length=30),
        ),
    ]
