# Generated by Django 4.2.7 on 2025-10-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0002_booking_tap_in_time_booking_tap_out_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_transaction',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tap_in_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tap_out_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tapped_in',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tapped_out',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='actual_arrival',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='actual_departure',
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_fare',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='journey',
            name='fare',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='journey',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
