# Generated by Django 4.2.7 on 2025-10-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0003_remove_booking_payment_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='total_seats',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
    ]
