# Generated by Django 4.2.7 on 2025-10-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0004_journey_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(max_length=20),
        ),
    ]
