# Generated by Django 4.2.7 on 2025-10-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_bus_bus_type'),
        ('routes', '0004_alter_stop_options_remove_route_created_at_and_more'),
        ('journeys', '0005_alter_booking_booking_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='buses.bus'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='routes.route'),
        ),
    ]
