# Generated by Django 4.2.7 on 2025-10-23 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0006_journey_cancellation_reason_alter_journey_bus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stage_order', models.PositiveIntegerField()),
                ('fare_from_previous', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='dropoff_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_bookings', to='journeys.stop'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_bookings', to='journeys.stop'),
        ),
    ]
