# Generated by Django 4.2.7 on 2025-10-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0006_journey_cancellation_reason_alter_journey_bus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
