# Generated by Django 4.2.7 on 2025-10-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0007_stop_alter_booking_dropoff_stop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dropoff_stop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_stop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Stop',
        ),
    ]
