# Generated by Django 4.2.7 on 2025-10-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0008_alter_booking_dropoff_stop_alter_booking_pickup_stop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
