# Generated by Django 4.2.7 on 2025-10-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0010_merge_0007_booking_base_fare_0009_booking_base_fare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='journey',
            options={'ordering': ['-created_at']},
        ),
    ]
