# Generated by Django 4.2.7 on 2025-10-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0011_alter_booking_options_alter_journey_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='available_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
