# Generated by Django 4.2.7 on 2025-10-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0013_faresession_delete_nfctransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tap_in_stop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tap_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tap_out_stop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tap_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
