# Generated by Django 4.2.7 on 2025-10-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0014_booking_tap_in_stop_booking_tap_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tapped_in',
            field=models.BooleanField(default=False),
        ),
    ]
