# Generated by Django 4.2.7 on 2025-10-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0015_booking_tapped_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='tapped_in_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
