# Generated by Django 4.2.7 on 2025-11-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0017_journeyrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JourneyRating',
        ),
    ]
